### ISSUE TITLE
Maximum Depth

### ISSUE THREAD

**Issue by tghoshmo** [pranjaldatta/DenseDepth-Pytorch#3]
Hi,

If the maximum depth is 10 meters, the upper limit for depth should be 10,000 millimeters. Instead, 1000 is used as the upper limit at various places. Could you please explain this discrepancy?

Thanks.

**Comment by pranjaldatta** [comment]
Hey @tghoshmo, I guess that's because the units used in the dataset are in `centimeters` (hence the 1000 is 1000 cm, which is equal to 10,000 mm, so in a way you are correct). You can find a bit more about this [here wherein the author of the paper tackles a similar question](https://github.com/ialhashim/DenseDepth/issues/69#issuecomment-541392634).

**Comment by tghoshmo** [comment]
@pranjaldatta Got it. Thanks for your prompt response!
